POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "Vivian",
  "idCard": "110102198702121234",
  "type": "2"
}


###
GET http://localhost:8000/member/passenger/query-list?page=2&size=2
Accept: application/json
token: {{token}}



###